### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by angel-yan** [zheniu/stochastic-cslr#2]
When I run quick_test.py,It just stuck like that. I don't know how to fix it. I've already downloaded all the model files. 

Traceback (most recent call last):
  File "/tmp/pycharm_project_338/quick_test.py", line 43, in <module>
    model = stochastic_cslr.load_model(args.model == "sfl")
  File "/tmp/pycharm_project_338/stochastic_cslr/__init__.py", line 19, in load_model
    model.load_state_dict(load_url(model_urls["sfl" if use_sfl else "dfl"]))
  File "/home/ysy/disk/ysy/miniconda3/envs/stochastic/lib/python3.7/site-packages/torch/hub.py", line 559, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/ysy/disk/ysy/miniconda3/envs/stochastic/lib/python3.7/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ysy/disk/ysy/miniconda3/envs/stochastic/lib/python3.7/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

Process finished with exit code 1

I don't know how to deal with it. Any idea, please?

**Comment by enhuiz** [comment]
load_url automatically download the model for you. It seems the cache is broken. Did you encounter a network connection break? You may check the path:

```
~/.cache/torch/hub/checkpoints/
```

To make sure the model is successfully downloaded. The md5 of the checkpoints are:

```
2d8dc0eb1e426487b3edfbf8fe95c6cb  dfl.pth
5401a14ae6a0d1ab925a054db345f075  sfl.pth
```

You may also download them [here](https://github.com/zheniu/stochastic-cslr-ckpt) and manually put them in the above directory.

**Comment by enhuiz** [comment]
Github seems to have a quota limitation for the LFS, switching to Google drive.

**Comment by zheniu** [comment]
Fixed by migrating the model to google drive: ec66eb8ede20f49374f635aa70e0a32c8b9c5489.
