### ISSUE TITLE
Can you please check this error?

### ISSUE THREAD

**Issue by jjayun** [zheniu/stochastic-cslr#3]
==> Vocab: {'A': 0, 'AACHEN': 1, 'AB': 2, 'AB-JETZT': 3, 'AB-PLUSPLUS': 4, 'ABEND': 5, 'ABER': 6, 'ABFALLEN': 7, 'ABSCHIED': 8, 'ABSCHNITT': 9, 'ABSINKEN': 10, 'ABWECHSELN': 11, 'ACH': 12, 'ACHT': 13, 'ACHTE': 14, 'ACHTHUNDERT': 15, 'ACHTUNG': 16, 'ACHTZEHN': 17, 'ACHTZIG': 18, 'AEHNLCH': 19, [...]
==> Vocab size: 1232
==> Dataset size: 5672
==> #params: 20991366
Train: 1/30:   0%|                                                                                                                                                                                                    | 0/709 [00:00<?, ?it/s]/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448272031/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/torchzq/runners/legacy.py:68: FutureWarning: Non-finite norm encountered in torch.nn.utils.clip_grad_norm_; continuing anyway. Note that the default behavior will change in a future release to error out if a non-finite total norm is encountered. At that point, setting error_if_nonfinite=false will be required to retain the old behavior.
  args.grad_clip_thres,
Train: 1/30:  16%|█████████████████████████████▍                                                                                                                                                            | 112/709 [03:25<18:14,  1.83s/it]
╰, iteration: 112
╰, ctc_loss: 6.686
╰, rif_loss: -10.14
╰, ent_loss: -0.01603
╰, bsl_loss: 40.41
╰, grad_norm: 19.87
╰, lr: 0.0001
Traceback (most recent call last):
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jygim/Workspace/stochastic-cslr/stochastic_cslr/runner.py", line 183, in <module>
    torchzq.start(Runner)
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/zouqi/core.py", line 206, in start
    for key, value in vars(command_args).items()
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/torchzq/runners/legacy.py", line 80, in train
    super().train(**kwargs)
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/torchzq/runners/base.py", line 326, in train
    for batch in pbar:
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/phoenix_datasets/datasets.py", line 96, in __getitem__
    frames = np.stack(list(frames))
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 297, in forward
    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 401, in resize
    return F_pil.resize(img, size=size, interpolation=pil_interpolation, max_size=max_size)
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/torchvision/transforms/functional_pil.py", line 241, in resize
    return img.resize(size[::-1], interpolation)
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/PIL/Image.py", line 1982, in resize
    self.load()
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/PIL/ImageFile.py", line 274, in load
    raise_oserror(err_code)
  File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/PIL/ImageFile.py", line 67, in raise_oserror
    raise OSError(message + " when reading image file")
OSError: broken data stream when reading image file

Thank you. Regards

**Comment by enhuiz** [comment]
It seems an image file is broken in your training set.

```
File "/home/jygim/miniconda3/envs/scslr/lib/python3.6/site-packages/PIL/ImageFile.py", line 67, in raise_oserror
raise OSError(message + " when reading image file")
OSError: broken data stream when reading image file
```

**Comment by jjayun** [comment]
Thank you so much !
